// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncmyogvinxvtysvkajkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbXlvZ3Zpbnh2dHlzdmthamtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNzM0MDAsImV4cCI6MjA3Nzg0OTQwMH0.BEl6QGd1SEFxOTqj7-ahMgyIgXUr8FfQZ0UWZYQdF-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});